name: Build

on: 
  push: 
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest
    container: centos:7.7.1908

    steps:
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout the Code
      uses: actions/checkout@v1
    - name: Build with Maven
      id: build_with_maven
//      run: mvn -B package --file pom.xml
      uses: LucaFeger/action-maven-cli@1.0.2
      with:
        cmd: mvn -B package --file pom.xml
