name: Build

on: 
  push: 
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Setup Java JDK
      id: setup_java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Checkout the Code
      id: checkout_the_code
      uses: actions/checkout@v1

    - name: Build with Maven
      id: build_with_maven
      run: mvn -B package --file pom.xml
