name: Build

on: 
  push: 
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu-latest

    steps:
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout the Code
      uses: actions/checkout@v1
    - name: Build with Maven
      run: mvn -B package --file pom.xml
