name: Build

on: 
  push: 
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest
    container: maven:3.3.9-jdk-8

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v1
    - name: Build with Maven
      run: mvn -B package --file pom.xml
