name: Release

on:
  push:
    tags: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Setup Java JDK
      id: setup_java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Checkout the Code
      id: checkout_the_code
      uses: actions/checkout@v1

    - name: Build with Maven
      id: build_with_maven
      run: mvn -B package --file pom.xml

    - name: Create the Release
      id: create_the_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Determine_the_version
      id: determine_the_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Upload the Asset
      id: upload_the_asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_the_release.outputs.upload_url }}
        asset_path: ./target/simple-app-${{ steps.determine_the_version.outputs.VERSION }}-mule-application.jar
        asset_name: simple-app-${{ steps.determine_the_version.outputs.VERSION }}-mule-application.jar
        asset_content_type: application/octet-stream